version: '3'
services:

  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:3000"

  server-dev:
    build:
      context: ./server
    restart: on-failure
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./var/www/html/contestFiles:/var/www/html/contestFiles
      - ./var/www/_logs/_logsDaily:/var/www/_logs/_logsDaily
      - ./server:/server
      - /server/node_modules


  mongo-dev:
    image: mongo:4.4.6-bionic
    ports:
      - "27017:27017"



  db-dev:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "5432:5432"

volumes:
  server-dev:
